### PR TITLE
Skip adding the language if is a byobu discussion

### PR DESCRIPTION
**Pull request by imorland**
Tested and confirmed working locally with `fof/byobu` `0.5.0` (Properly this time)

### CODE REVIEW

**Comment by datitisev** [comment]
Can you use `Arr::get` for the properties? I'd prefer that :).

**Comment by imorland** [comment]
Done :)

**Comment by datitisev** [comment]
Hm I guess Arr::has would've worked too lol. Either works, this looks good to me :+1:.

**Comment by imorland** [comment]
Great, thanks!

**Pull request merged**
